// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhwwllwyavmodhrcqyea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5od3dsbHd5YXZtb2RocmNxeWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDYzNzMsImV4cCI6MjA1OTE4MjM3M30.3h9DIEg5hLQG6PK1MYyqD8CDw9jQvJgObCBiqL2voOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);